### ISSUE TITLE
Tutorial?

### ISSUE THREAD

**Issue by stbatuhan** [piet-v/HueLightPlus#4] opened 2017-09-11 18:12 UTC
Can you make a tutorial and also can you add a button for the application close?

**Comment by piet-v** [comment] 2017-09-12 20:10
@stbatuhan 

I tried to explain a bit more with latest release, hope this is enough for now?

https://github.com/piet-v/HueLightPlus/releases/latest

Only thing that's a bit confusing at the moment is the config.json. A UI to edit it is planned. :)

Not sure what u mean with the closing button? There's the default 'X to close' button on top right? Right clicking on the icon in the system tray also gives the option to Close the application.

**Comment by stbatuhan** [comment] 2017-09-13 07:54
That might be not the problem now bec i checked your code and i saw form1 :) That's the thing i missed bec on my comp there is no ui. I will look to that when i go back home .

Right click on the icon is also not working on my comp :/ So there is something missing in my comp :/ I will try build from solution file i hope :)

**Comment by theshorterbus** [comment] 2017-09-26 03:30
Can't seem to have any luck with the software. Installation seems fairly straightforward, including the setup. However LEDs aren't changing, and every time I open the .exe and look at my system tray it disappears shortly after. Tried uninstalling everything, rebooting after any change, including cam software (tried with and without) and dfmirage. Also can I just omit or comment out the bottom panel if I'm not using it? I only have one channel and device and just tried moving bottom to the one I don't have, also tried just removing bottom section from script. Any advice what I could be doing wrong?

**Comment by piet-v** [comment] 2017-09-26 11:58
Any chance you could show me your config.json file? It sounds like a malformed json structure. You can post it to https://pastebin.com/ or something similar.

The application should log to log.txt on exit/crash. You can paste the one too, it should contain the crash reason.

I've been a bit busy irl so haven't had much time to take a look a GUI for editing the LED setup yet. I'll be releasing a new release with a realtime LED preview image today/tomorrow with some blinking LED fixes.

**Comment by theshorterbus** [comment] 2017-09-26 14:58
So [this](https://pastebin.com/embed_js/70xm9WSB) was the json config where I tried changing the bottom leds to the different panel as I wasn't using a bottom row. 

and [here](https://pastebin.com/embed_js/Q2gzhmnj) is where I removed bottom config from the script altogether.

Lastly, I also tried [this](https://pastebin.com/embed_js/Ddn4dQrr) , where I left the bottom in and kept on the same device but a different channel.

I, of course, played around with the delay, etc also, but for the most part, these are the 3 configs I tried.
I should have thought to look for a debug file, but can't access my TeamViewer atm, so I will post later when I get home.

**Comment by piet-v** [comment] 2017-09-26 20:35
Ah, think I know what's happening here. Your config sets up 2 devices. One on COM8 and one on COM3. if you only have 1 device it's probly crashing while trying to connect to the non-existing device.

The isEnabled prop is more like a startEnabled property. The app will still open the connection to the COM port but won't update the LEDS.

Guess that's on me for not clarifying the prop enough.

SOLUTION: Could you try to remove one device object? Something like this: (filling in the correct portname)

 "devices": [
    {
      "port": "COM8",
      "isEnabled": true
    }
  ]

**Comment by theshorterbus** [comment] 2017-09-27 17:53
I retyped it and following your instructions and it worked. Not sure if it's specifically the cause or just a fresh rework that fixed it. I have noticed it won't work at all if I remove the bottom LEDs from the script though, so I'm running them on a separate channel that doesn't exist.

**Comment by piet-v** [comment] 2017-09-27 20:43
Ye it currently doesn't handle malformed JSON that well. It seems a better idea to just implement an editor than spending time on handling this. As for your bottom led issue.

The current implementation expects the screen to have a bottom; which can have zero regions. This should work:

"bottom": {
      "screenRegions": [
      ]
}

**Comment by piet-v** [comment] 2017-09-27 20:45
Closing this issue. The latest release notes are a bit more clear. Most mistakes are now made in the config.json which will be solved with an editor (someday)

**Closed as completed by piet-v** 2017-09-27 20:45 UTC
